//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutMenuHeader {
            get {
                return ResourceManager.GetString("AboutMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About program.
        /// </summary>
        public static string AboutToolTip {
            get {
                return ResourceManager.GetString("AboutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding a row is not allowed.
        /// </summary>
        public static string Adding_a_row_is_not_allowed {
            get {
                return ResourceManager.GetString("Adding_a_row_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Number (F1).
        /// </summary>
        public static string ArticleNumber {
            get {
                return ResourceManager.GetString("ArticleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Copy.
        /// </summary>
        public static string CopyHeader {
            get {
                return ResourceManager.GetString("CopyHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy selected value to clip board.
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Context.
        /// </summary>
        public static string Created_Context {
            get {
                return ResourceManager.GetString("Created_Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Cut.
        /// </summary>
        public static string CutHeader {
            get {
                return ResourceManager.GetString("CutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut selected value to clip board.
        /// </summary>
        public static string CutToolTip {
            get {
                return ResourceManager.GetString("CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Delete.
        /// </summary>
        public static string DeleteMenuHeader {
            get {
                return ResourceManager.GetString("DeleteMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected article number.
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a row is not allowed.
        /// </summary>
        public static string Deleting_a_row_is_not_allowed {
            get {
                return ResourceManager.GetString("Deleting_a_row_is_not_allowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenuHeader {
            get {
                return ResourceManager.GetString("EditMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Property Name {0} : Error Message: {1}.
        /// </summary>
        public static string Error_Property_Name_0__Error_Message_1 {
            get {
                return ResourceManager.GetString("Error_Property_Name_0__Error_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Saving to Database: {0}.
        /// </summary>
        public static string Error_Saving_to_Database_0 {
            get {
                return ResourceManager.GetString("Error_Saving_to_Database_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ExitMenuHeader {
            get {
                return ResourceManager.GetString("ExitMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit program.
        /// </summary>
        public static string ExitToolTip {
            get {
                return ResourceManager.GetString("ExitToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenuHeader {
            get {
                return ResourceManager.GetString("FileMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterButtonHeader {
            get {
                return ResourceManager.GetString("FilterButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterHeader {
            get {
                return ResourceManager.GetString("FilterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindButtonHeader {
            get {
                return ResourceManager.GetString("FindButtonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadLaserData: {0}.
        /// </summary>
        public static string LoadLaserData_0 {
            get {
                return ResourceManager.GetString("LoadLaserData_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadLaserDataFiltered: {0}.
        /// </summary>
        public static string LoadLaserDataFiltered_0 {
            get {
                return ResourceManager.GetString("LoadLaserDataFiltered_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoadLaserDataFiltered exception.
        /// </summary>
        public static string LoadLaserDataFiltered_exception {
            get {
                return ResourceManager.GetString("LoadLaserDataFiltered_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New From Selected.
        /// </summary>
        public static string NewFromSelectedMenuHeader {
            get {
                return ResourceManager.GetString("NewFromSelectedMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new article number and copy the values from the selected.
        /// </summary>
        public static string NewFromSelectedToolTip {
            get {
                return ResourceManager.GetString("NewFromSelectedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string NewMenuHeader {
            get {
                return ResourceManager.GetString("NewMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New article number.
        /// </summary>
        public static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _OnTop.
        /// </summary>
        public static string OnTopMenuHeader {
            get {
                return ResourceManager.GetString("OnTopMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window Always On Top.
        /// </summary>
        public static string OnTopToolTip {
            get {
                return ResourceManager.GetString("OnTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of memory! Please use a filter to make selection smaller!.
        /// </summary>
        public static string Out_of_memory_Please_use_a_filter_to_make_selection_smaller {
            get {
                return ResourceManager.GetString("Out_of_memory_Please_use_a_filter_to_make_selection_smaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Paste.
        /// </summary>
        public static string PasteHeader {
            get {
                return ResourceManager.GetString("PasteHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste from clip board.
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string RefreshMenuHeader {
            get {
                return ResourceManager.GetString("RefreshMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh database.
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveChanges Exception.
        /// </summary>
        public static string SaveChanges_Exception {
            get {
                return ResourceManager.GetString("SaveChanges_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string SaveMenuHeader {
            get {
                return ResourceManager.GetString("SaveMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes to database.
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string SearchHeader {
            get {
                return ResourceManager.GetString("SearchHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Window.
        /// </summary>
        public static string WindowMenuHeader {
            get {
                return ResourceManager.GetString("WindowMenuHeader", resourceCulture);
            }
        }
    }
}
