//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCMarker.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DCMarker.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string AboutMenuHeader {
            get {
                return ResourceManager.GetString("AboutMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddHistroyDataToDB Exception.
        /// </summary>
        public static string AddHistroyDataToDB_Exception {
            get {
                return ResourceManager.GetString("AddHistroyDataToDB_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article {0} received.
        /// </summary>
        public static string Article_0_received {
            get {
                return ResourceManager.GetString("Article_0_received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article does not exist in database!.
        /// </summary>
        public static string Article_does_not_exist_in_database {
            get {
                return ResourceManager.GetString("Article_does_not_exist_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not defined in database {0}.
        /// </summary>
        public static string Article_not_defined_in_database_0 {
            get {
                return ResourceManager.GetString("Article_not_defined_in_database_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not defined in database! Article={0}.
        /// </summary>
        public static string Article_not_defined_in_database_Article0 {
            get {
                return ResourceManager.GetString("Article_not_defined_in_database_Article0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Number.
        /// </summary>
        public static string ArticleNumber {
            get {
                return ResourceManager.GetString("ArticleNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string BatchDone {
            get {
                return ResourceManager.GetString("BatchDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string BatchSize {
            get {
                return ResourceManager.GetString("BatchSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateSerialNumber Exception.
        /// </summary>
        public static string CreateSerialNumber_Exception {
            get {
                return ResourceManager.GetString("CreateSerialNumber_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edge marking is not supported in this version!.
        /// </summary>
        public static string Edge_marking_is_not_supported_in_this_version {
            get {
                return ResourceManager.GetString("Edge_marking_is_not_supported_in_this_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error initializing machine.
        /// </summary>
        public static string Error_initializing_machine {
            get {
                return ResourceManager.GetString("Error_initializing_machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading layout: {0}.
        /// </summary>
        public static string Error_loading_layout_0 {
            get {
                return ResourceManager.GetString("Error_loading_layout_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Property Name {0} : Error Message: {1}.
        /// </summary>
        public static string Error_Property_Name_0__Error_Message_1 {
            get {
                return ResourceManager.GetString("Error_Property_Name_0__Error_Message_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Exit.
        /// </summary>
        public static string ExitMenuHeader {
            get {
                return ResourceManager.GetString("ExitMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenuHeader {
            get {
                return ResourceManager.GetString("FileMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixture.
        /// </summary>
        public static string Fixture {
            get {
                return ResourceManager.GetString("Fixture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string HelpMenuHeader {
            get {
                return ResourceManager.GetString("HelpMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemInPlace signal received before Article Number is set.
        /// </summary>
        public static string ItemInPlace_received_before_Article_Number_is_set {
            get {
                return ResourceManager.GetString("ItemInPlace_received_before_Article_Number_is_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edges.
        /// </summary>
        public static string Kant {
            get {
                return ResourceManager.GetString("Kant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout not defined for this article! Article={0}.
        /// </summary>
        public static string Layout_not_defined_for_this_article_Article0 {
            get {
                return ResourceManager.GetString("Layout_not_defined_for_this_article_Article0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded.
        /// </summary>
        public static string Loaded {
            get {
                return ResourceManager.GetString("Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marking is done!.
        /// </summary>
        public static string Marking_is_done {
            get {
                return ResourceManager.GetString("Marking_is_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid number.
        /// </summary>
        public static string Not_a_valid_number {
            get {
                return ResourceManager.GetString("Not_a_valid_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Top.
        /// </summary>
        public static string OnTopMenuHeader {
            get {
                return ResourceManager.GetString("OnTopMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity must be 1 or larger.
        /// </summary>
        public static string Quantity_must_be_1_or_larger {
            get {
                return ResourceManager.GetString("Quantity_must_be_1_or_larger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset IO.
        /// </summary>
        public static string ResetIOMenuHeader {
            get {
                return ResourceManager.GetString("ResetIOMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test Item.
        /// </summary>
        public static string TestItem {
            get {
                return ResourceManager.GetString("TestItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCMarker.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TO.
        /// </summary>
        public static string ToNumber {
            get {
                return ResourceManager.GetString("ToNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Tools.
        /// </summary>
        public static string ToolsMenuHeader {
            get {
                return ResourceManager.GetString("ToolsMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of machine not available! Type={0}.
        /// </summary>
        public static string Type_of_machine_not_available_Type0 {
            get {
                return ResourceManager.GetString("Type_of_machine_not_available_Type0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update didn&apos;t work on this article and layout! Article={0}, Layout={1}.
        /// </summary>
        public static string Update_didnt_work_on_this_article_and_layout_Article0_Layout1 {
            get {
                return ResourceManager.GetString("Update_didnt_work_on_this_article_and_layout_Article0_Layout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for product.
        /// </summary>
        public static string Waiting_for_product {
            get {
                return ResourceManager.GetString("Waiting_for_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for start signal ({0}).
        /// </summary>
        public static string Waiting_for_start_signal_0 {
            get {
                return ResourceManager.GetString("Waiting_for_start_signal_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for start signal ({0}.xlp).
        /// </summary>
        public static string Waiting_for_start_signal_0xlp {
            get {
                return ResourceManager.GetString("Waiting_for_start_signal_0xlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Windows.
        /// </summary>
        public static string WindowMenuHeader {
            get {
                return ResourceManager.GetString("WindowMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlp.
        /// </summary>
        public static string xlp {
            get {
                return ResourceManager.GetString("xlp", resourceCulture);
            }
        }
    }
}
